// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Premialo.Server.Models;

#nullable disable

namespace Premialo.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251118191126_Agregando booleano")]
    partial class Agregandobooleano
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Premialo.Server.DTOs.Asistencia.ConsultaCedulaDTO", b =>
                {
                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("Premialo.Server.Models.Asistencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SorteoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("int");

                    b.Property<bool>("participante")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("SorteoId");

                    b.HasIndex("UsuarioCreacionId");

                    b.ToTable("Asistencias");
                });

            modelBuilder.Entity("Premialo.Server.Models.Participante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentoIdentidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SorteoId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnidadOrganizativa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SorteoId");

                    b.HasIndex("UsuarioCreacionId");

                    b.HasIndex("DocumentoIdentidad", "SorteoId")
                        .IsUnique();

                    b.ToTable("Participantes");
                });

            modelBuilder.Entity("Premialo.Server.Models.Premio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutaFoto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SorteoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("int");

                    b.Property<int>("orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SorteoId");

                    b.HasIndex("UsuarioCreacionId");

                    b.ToTable("Premios");
                });

            modelBuilder.Entity("Premialo.Server.Models.Sorteo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSorteo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioModificacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.HasIndex("UsuarioCreacionId");

                    b.HasIndex("UsuarioModificacionId");

                    b.ToTable("Sorteos");
                });

            modelBuilder.Entity("Premialo.Server.Models.SorteoResultado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("ParticipanteId")
                        .HasColumnType("int");

                    b.Property<int>("PremioId")
                        .HasColumnType("int");

                    b.Property<int>("SorteoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParticipanteId")
                        .IsUnique();

                    b.HasIndex("PremioId")
                        .IsUnique();

                    b.HasIndex("UsuarioCreacionId");

                    b.HasIndex("SorteoId", "PremioId", "ParticipanteId")
                        .IsUnique();

                    b.ToTable("SorteosResultados");
                });

            modelBuilder.Entity("Premialo.Server.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("BloqueadoHasta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPassword")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimoAcceso")
                        .HasColumnType("datetime2");

                    b.Property<int>("IntentosLogin")
                        .HasColumnType("int");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellidos = "Sistema",
                            Email = "admin@contraloria.gob.do",
                            Estatus = 1,
                            FechaCreacion = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaPassword = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IntentosLogin = 0,
                            MustChangePassword = false,
                            Nombres = "Administrador",
                            PasswordHash = "$2a$11$AfiMaYqby6eas.iVnYAdkO./0MRqoicDE8VrOqLgTisXL00Y9vFYy",
                            Rol = 1,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Premialo.Server.Models.Asistencia", b =>
                {
                    b.HasOne("Premialo.Server.Models.Sorteo", "Sorteo")
                        .WithMany("Asistencias")
                        .HasForeignKey("SorteoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Premialo.Server.Models.Usuario", "UsuarioCreacion")
                        .WithMany("Asistencias")
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Sorteo");

                    b.Navigation("UsuarioCreacion");
                });

            modelBuilder.Entity("Premialo.Server.Models.Participante", b =>
                {
                    b.HasOne("Premialo.Server.Models.Sorteo", "Sorteo")
                        .WithMany("Participantes")
                        .HasForeignKey("SorteoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Premialo.Server.Models.Usuario", "UsuarioCreacion")
                        .WithMany("ParticipantesCreados")
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Sorteo");

                    b.Navigation("UsuarioCreacion");
                });

            modelBuilder.Entity("Premialo.Server.Models.Premio", b =>
                {
                    b.HasOne("Premialo.Server.Models.Sorteo", "Sorteo")
                        .WithMany("Premios")
                        .HasForeignKey("SorteoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Premialo.Server.Models.Usuario", "UsuarioCreacion")
                        .WithMany("PremiosCreados")
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Sorteo");

                    b.Navigation("UsuarioCreacion");
                });

            modelBuilder.Entity("Premialo.Server.Models.Sorteo", b =>
                {
                    b.HasOne("Premialo.Server.Models.Usuario", "UsuarioCreacion")
                        .WithMany("SorteosCreados")
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Premialo.Server.Models.Usuario", "UsuarioModificacion")
                        .WithMany("SorteosEditados")
                        .HasForeignKey("UsuarioModificacionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("UsuarioCreacion");

                    b.Navigation("UsuarioModificacion");
                });

            modelBuilder.Entity("Premialo.Server.Models.SorteoResultado", b =>
                {
                    b.HasOne("Premialo.Server.Models.Participante", "Participante")
                        .WithOne("Resultado")
                        .HasForeignKey("Premialo.Server.Models.SorteoResultado", "ParticipanteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Premialo.Server.Models.Premio", "Premio")
                        .WithOne("Resultado")
                        .HasForeignKey("Premialo.Server.Models.SorteoResultado", "PremioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Premialo.Server.Models.Sorteo", "Sorteo")
                        .WithMany("Resultados")
                        .HasForeignKey("SorteoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Premialo.Server.Models.Usuario", "UsuarioCreacion")
                        .WithMany("ResultadosCreados")
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Participante");

                    b.Navigation("Premio");

                    b.Navigation("Sorteo");

                    b.Navigation("UsuarioCreacion");
                });

            modelBuilder.Entity("Premialo.Server.Models.Participante", b =>
                {
                    b.Navigation("Resultado");
                });

            modelBuilder.Entity("Premialo.Server.Models.Premio", b =>
                {
                    b.Navigation("Resultado")
                        .IsRequired();
                });

            modelBuilder.Entity("Premialo.Server.Models.Sorteo", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("Participantes");

                    b.Navigation("Premios");

                    b.Navigation("Resultados");
                });

            modelBuilder.Entity("Premialo.Server.Models.Usuario", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("ParticipantesCreados");

                    b.Navigation("PremiosCreados");

                    b.Navigation("ResultadosCreados");

                    b.Navigation("SorteosCreados");

                    b.Navigation("SorteosEditados");
                });
#pragma warning restore 612, 618
        }
    }
}
